version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nodejs-aws-codedeploy-pipeline
hooks:
# ApplicationStop:
# DownloadBundle:
#  BeforeInstall:
#    - location: scripts/before_install.sh
#      timeout: 300
#      runas: root
# Install:
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: root
# ValidateService:
