version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      # Add any necessary installation commands here
  pre_build:
    commands:
      - echo Pre-build phase...
      # Add any necessary pre-build commands here
  build:
    commands:
      - echo Build phase...
      # Add any build commands here if needed
  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
  base-directory: .
  discard-paths: no

cache:
  paths: []
