version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Change this if you're using a different runtime
    commands:
      - echo "No dependencies to install."

  pre_build:
    commands:
      - echo "Pre-build phase: Nothing to do here."

  build:
    commands:
      - echo "Build phase: Nothing to build for a static HTML page."

  post_build:
    commands:
      - echo "Post-build phase: Copying files to the deployment directory."
      - mkdir -p /var/www/html/demo
      - cp -r * /var/www/html/demo/

artifacts:
  files:
    - '**/*'
  base-directory: .  # Change to your source directory if different

cache:
  paths: []
