version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running linting...
      - npm run lint
  build:
    commands:
      - echo Running build script...
      - npm run build
      - echo Running tests...
      - npm test
  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'
