version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

    commands:
      - aws --version

  pre_build:
    commands:
      - echo pre Building application

  build:
    commands:
      - echo Building application

  post_build:
    commands:
      - echo Deploying Project

artifacts:
  files: '**/*'
  name: basic-node-project
  discard-paths: yes
  base-directory: .