steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'index.html', 'gs://demo-cicd-bucket/Repo/index.html']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['deploy.sh']

options:
  logging: CLOUD_LOGGING_ONLY
